モデルの定義を`@nitic-astronomy/model`パッケージに切り分けた。
astronomy-club-at-nitic/nitic-astronomy pull request #106
Opened 2023-04-20 14:05 UTC by ReoHakase

- close #102 
- close #101

2023-04-21 02:06 UTC, dino3616 requested changes
コメ1, リクチェン1っすー
(ところでモデルが空なのはなぜ？)

2023-04-21 02:06 UTC, dino3616 commented on packages/tsconfig/tsconfig.base.json
> +      "~model/*": ["../model/src/*"]
`@nitic-astronomy/jest` と `~cms` があるのパッと見で違いわからないので、やっぱ `@nitic-astronomy/**` で統一したい〜

```suggestion
      "@nitic-astronomy/cms/*": ["../cms/src/*"],
      "@nitic-astronomy/model/*": ["../model/src/*"]
```

2023-04-21 04:07 UTC, ReoHakase commented
> コメ1, リクチェン1っすー (ところでモデルが空なのはなぜ？)

`packages/cms/src/model`のこと？それは意図した通り

2023-04-21 04:11 UTC, ReoHakase commented on packages/tsconfig/tsconfig.base.json
> +      "~model/*": ["../model/src/*"]
`package.json`の`exports`フィールドで指定したものと区別できなくなるからやめた方がいいと思う

> `@nitic-astronomy/jest` と `~cms` があるのパッと見で違いわからないので、やっぱ `@nitic-astronomy/**` で統一したい〜

`package.json`の`exports`フィールドで指定したものと区別できなくなるからやめた方がいいと思う

2023-04-21 07:49 UTC, dino3616 commented on packages/tsconfig/tsconfig.base.json
> +      "~model/*": ["../model/src/*"]
んーというと？？

2023-04-21 07:50 UTC, dino3616 commented
> `packages/cms/src/model`のこと？それは意図した通りかなー

もう決めてもいいかなと思ったけど、まぁ今じゃないよなという判断であればあっpろゔぇっすー

2023-04-24 01:15 UTC, dino3616 commented on packages/tsconfig/tsconfig.base.json
> +      "~model/*": ["../model/src/*"]
あーーなるほどね〜〜〜〜
であれば `~` だと ぱっと見 `~/**` っぽくもあるので、`#` or `#/` がいいっす

2023-04-24 01:15 UTC, dino3616 commented
> 全て@nitic-astronomy/modelで定義されているモデルを参照するように変更したから、packages/cms/src/modelは廃止するって意味で言った

あーー勘違いっす！ご放念！

2023-04-25 07:47 UTC, ReoHakase commented on packages/tsconfig/tsconfig.base.json
> +      "~model/*": ["../model/src/*"]
対応しました😎

2023-04-26 05:10 UTC, dino3616 approved these changes
あっp・ろゔぇ

2023-04-26 05:25 UTC, merged