メンバー関連のコンポーネント群`<MemberIcon>` `<MemberSummary>` `<MemberCard>`を作成した。
astronomy-club-at-nitic/nitic-astronomy pull request #166
Opened 2023-05-05 11:47 UTC by ReoHakase

- close #131 #132 #133

<img width="79" alt="image" src="https://user-images.githubusercontent.com/16751535/236449587-68f9b056-6800-4b25-9694-77b7c340defc.png">
<img width="180" alt="image" src="https://user-images.githubusercontent.com/16751535/236449637-4d4fef2e-cfb9-4d88-aa2f-1f14d427f1ff.png">
<img width="413" alt="image" src="https://user-images.githubusercontent.com/16751535/236449681-9bcd9adf-b0e3-4487-9ecb-7cc5bfc674f6.png">

2023-05-08 00:46 UTC, dino3616 requested changes

2023-05-08 00:46 UTC, dino3616 commented on apps/website/.storybook/storybook-global.css
> +  @apply bg-keyplate-2 text-keyplate-12 font-main;
純粋な質問で、なぜに `apply` ？？

2023-05-08 00:46 UTC, dino3616 commented on apps/website/src/module/member/ui/component/member-external-link/member-external-link.presenter.tsx
> +  if (!url) return 'other';
```suggestion
  if (!url) {
    return 'other';
  }
```

2023-05-08 00:46 UTC, dino3616 commented on apps/website/src/module/member/ui/component/member-external-link/member-external-link.presenter.tsx
> +  if (!urlString) return 'other';
```suggestion
  if (!urlString) {
    return 'other';
  }
```

2023-05-08 00:46 UTC, dino3616 commented on apps/website/src/module/member/ui/component/member-external-link/member-external-link.presenter.tsx
> +  if (!urlObject || !urlObject.hostname) return undefined;
```suggestion
  if (!urlObject || !urlObject.hostname) {
    return undefined;
  }
```

2023-05-08 00:46 UTC, dino3616 commented on apps/website/src/module/member/ui/component/member-card/member-card.presenter.tsx
> +  <li className={twMerge('flex flex-col items-stretch gap-2 rounded-lg bg-keyplate-1 p-6 shadow-floating', className)} {...props}>
`MemberCard` からしたらリストかそうじゃないかは関心事じゃない (外部からリストかリストじゃないかを変えられるべき) なので、 `div` でもよくないかとは思う

それか `MemberCardListItem` にして `<li>` であることを命名で強調されてるとわかりやすいかなぁ

あとは props 経由でラッパを注入する方法もあるっちゃある
https://zenn.dev/sho_ts/articles/ff3082b1e3db5f

```suggestion
  <div className={twMerge('flex flex-col items-stretch gap-2 rounded-lg bg-keyplate-1 p-6 shadow-floating', className)} {...props}>
```

2023-05-08 07:12 UTC, ReoHakase commented on apps/website/.storybook/storybook-global.css
> +  @apply bg-keyplate-2 text-keyplate-12 font-main;
`.storybook/main.ts`のデコレータにクラス名追加しても、キャンバス全体には適応されないからマージン部分に素の色が残っちゃって気持ち悪いんだよね

```tsx
const preview: Preview = {
  decorators: [
    (Story) => (
      <ThemeProvider attribute="data-theme">
        <div className={fontFamily}>
          <Story />
        </div>
      </ThemeProvider>
    ),
  ],
  parameters: {
    viewport: {
      viewports: INITIAL_VIEWPORTS,
    },
  },
};
```

2023-05-08 07:12 UTC, ReoHakase commented on apps/website/src/module/member/ui/component/member-external-link/member-external-link.presenter.tsx
> +  if (!url) return 'other';
せやな

2023-05-08 07:24 UTC, ReoHakase commented on apps/website/src/module/member/ui/component/member-external-link/member-external-link.presenter.tsx
> +  if (!url) return 'other';
https://github.com/astronomy-club-at-nitic/nitic-astronomy/pull/166/commits/547412ed93bf2a7da408e9718decc9f9483124ff

2023-05-08 07:24 UTC, ReoHakase commented on apps/website/src/module/member/ui/component/member-external-link/member-external-link.presenter.tsx
> +  if (!urlObject || !urlObject.hostname) return undefined;
https://github.com/astronomy-club-at-nitic/nitic-astronomy/pull/166/commits/547412ed93bf2a7da408e9718decc9f9483124ff

2023-05-08 07:25 UTC, ReoHakase commented on apps/website/src/module/member/ui/component/member-external-link/member-external-link.presenter.tsx
> +  if (!urlString) return 'other';
https://github.com/astronomy-club-at-nitic/nitic-astronomy/pull/166/commits/547412ed93bf2a7da408e9718decc9f9483124ff

2023-05-08 07:25 UTC, ReoHakase commented on apps/website/src/module/member/ui/component/member-card/member-card.presenter.tsx
> +  <li className={twMerge('flex flex-col items-stretch gap-2 rounded-lg bg-keyplate-1 p-6 shadow-floating', className)} {...props}>
https://github.com/astronomy-club-at-nitic/nitic-astronomy/pull/166/commits/a3c282abc47f90c1e6aab3d031ab7d1313c5cc3b

2023-05-10 00:40 UTC, dino3616 requested changes

2023-05-10 00:40 UTC, dino3616 commented on apps/website/src/module/member/ui/component/member-summary/member-summary.presenter.tsx
> +);
こっちもでおなしゃすー

```suggestion
export const MemberSummary: FC<MemberSummaryProps> = ({ name, icon, role, count, className, ...props }) => (
  <li className={twMerge('flex flex-row items-center gap-2.5', className)} {...props}>
    {icon ? (
      <MemberIcon src={icon.url} width={icon.width ?? 64} height={icon.height ?? 64} alt={`${name} のアイコン`} />
    ) : (
      <MemberIcon src={SquareLightLogoImage} placeholder="blur" alt={'デフォルトの部員アイコン'} />
    )}
    <div className="flex flex-col items-start justify-center gap-0">
      <p>{name}</p>
      {role && <p className="text-small text-keyplate-11">{role}</p>}
    </div>
    {count && (
      <Tag color="keyplate" aria-label={`著者は他にも${count}名います。`} className="text-small font-bold">
        +{count}名
      </Tag>
    )}
  </li>
);
```

2023-05-10 00:43 UTC, dino3616 commented on apps/website/.storybook/storybook-global.css
> +  @apply bg-keyplate-2 text-keyplate-12 font-main;
あ〜〜〜なるほど。。
ぱっと見でどこまでがコンポーネントかわからなくなるかもとか思ったけどまぁ大丈夫かぁ
あっpろゔぇで👍

2023-05-10 02:18 UTC, ReoHakase commented on apps/website/src/module/member/ui/component/member-summary/member-summary.presenter.tsx
> +);
https://github.com/astronomy-club-at-nitic/nitic-astronomy/pull/166/commits/a30a3b95cc9ea2f6abfe57c2f2e7e7770bc748bd

2023-05-10 03:20 UTC, dino3616 approved these changes
あっpろゔぇ

2023-05-10 03:20 UTC, merged