MicroCMSからのデータフェッチを担うパッケージ`cms`を作成した
astronomy-club-at-nitic/nitic-astronomy pull request #94
Opened 2023-04-15 16:57 UTC by ReoHakase

- close #93 

```ts
export type { Article, ArticleDetail } from '@/model/article.model';
export type { Member } from '@/model/member.model';
export type { Tag } from '@/model/tag.model';

export { ArticleSchema, ArticleDetailSchema } from '@/model/article.model';
export { MemberSchema } from '@/model/member.model';
export { TagSchema } from '@/model/tag.model';

export { getArticles } from '@/service/article/get-articles.service';
export type { GetArticlesQuery, GetArticlesResponse, GetArticles } from '@/service/article/get-articles.service';
export { getArticleIds } from '@/service/article/get-article-ids.service';
export type { GetArticleIdsResponse, GetArticleIds } from '@/service/article/get-article-ids.service';
export { getArticleDetail } from '@/service/article/get-article-detail.service';
export type { GetArticleDetailQuery, GetArticleDetailResponse, GetArticleDetail } from '@/service/article/get-article-detail.service';

export { getMembers } from '@/service/member/get-members.service';
export type { GetMembersQuery, GetMembersResponse, GetMembers } from '@/service/member/get-members.service';

export { getTags } from '@/service/tag/get-tags.service';
export type { GetTagsQuery, GetTagsResponse, GetTags } from '@/service/tag/get-tags.service';
export { getTagIds } from '@/service/tag/get-tag-ids.service';
export type { GetTagIdsResponse, GetTagIds } from '@/service/tag/get-tag-ids.service';
export { getTagDetail } from '@/service/tag/get-tag-detail.service';
export type { GetTagDetailQuery, GetTagDetailResponse, GetTagDetail } from '@/service/tag/get-tag-detail.service';
```

2023-04-17 04:24 UTC, dino3616 requested changes
AAAパターンとZodの導入はGoodです 👍
ただいくつかサジェスチョンしたので確認よろ
加えてテストが落ちてる (yamlと リポジトリに環境変数設定されてない？) のでそっちの対応もよろしくっす

それはそうとお身体お大事に。。🍵

2023-04-17 04:26 UTC, ReoHakase commented on .vscode/settings.json
> +  "eslint.workingDirectories": ["apps/website/", "packages/microcms"],
そうだね

2023-04-17 04:31 UTC, ReoHakase commented on packages/cms/tsconfig.json
> +    "declarationMap": true,
#67 別にこのパッケージ自体ではnext使ってないから入れなくていいかなと思ってたけど、これを`apps/website`から呼び出した時にtsエラー出るとめんどいし入れとこうか

2023-04-17 04:37 UTC, ReoHakase commented
> AAAパターンとZodの導入はGoodです 👍 ただいくつかサジェスチョンしたので確認よろ 加えてテストが落ちてる (yamlと リポジトリに環境変数設定されてない？) のでそっちの対応もよろしくっす
> 
> それはそうとお身体お大事に。。🍵

多分環境変数の設定するための権限持ってないからできない🥺

2023-04-17 04:40 UTC, ReoHakase commented on packages/cms/src/service/article/get-article-ids.service.ts
> +// export type GetArticleIdsQuery = never;
消し忘れです

2023-04-17 04:40 UTC, dino3616 commented
あーやっぱり
じゃぁ secret の方はやっとくので workflows の方やってもらえれば 🙏

2023-04-17 04:46 UTC, ReoHakase commented
> あーやっぱり じゃぁ secret の方はやっとくので workflows の方やってもらえれば 🙏

https://github.com/astronomy-club-at-nitic/nitic-astronomy/pull/94/commits/3fbd4676fd0b11115753479c50bdeda93d617a2f

あとはよろしく^^

2023-04-17 04:55 UTC, ReoHakase commented on packages/cms/src/service/article/get-article-detail.service.spec.ts
> +  test.skip('should return an article with content body in expected schema', async () => {
特定の記事の取得の機能をテストするためには、当然(モックを作らない限り)(めんどそう)MicroCMS側で対象となる記事・タグを用意しなければならないよね？

だけど、テスト用の記事・タグを残しておかないといけない状況は、この先の引き継ぎと運用を考えた時に好ましくないじゃん？

以上の理由でテスト用のコードは残しつつ実行されないように`.skip()`入れてます。

<img width="1590" alt="image" src="https://user-images.githubusercontent.com/16751535/232381305-50022d0c-b23a-4485-a304-189490d24235.png">


<img width="1592" alt="image" src="https://user-images.githubusercontent.com/16751535/232380921-99ae7c37-f7ad-4497-a65c-5a4486a367b3.png">

2023-04-18 05:31 UTC, ReoHakase commented on packages/cms/src/service/article/get-article-ids.service.ts
> +
後からリファクタリングをしたとしても、この`cms`パッケージが外部に公開するもののインターフェースは変わらないと思うから、一旦`cms`パッケージ内のコードの整理は後回しにしたいです

2023-04-18 05:52 UTC, dino3616 commented on packages/cms/src/service/article/get-article-detail.service.spec.ts
> +  test.skip('should return an article with content body in expected schema', async () => {
- Service → External のテストでは通信できるか・パースできるかがテスト項目になるので、モックを作る必要はない
- 実際にリクエストを送るとなると複数環境作れるとベストだけど、その場合月々万単位のお支払いとなる
- であれば「[DO NOT USE] test article 1」とか作るのもアリ

など思ったけど本番環境の中にテスト用のカラムがちらほらしてるのはまぁ耐え難いので `.skip()` でいっかぁ。。

2023-04-18 05:52 UTC, dino3616 submitted a review, later dismissed
LGTMスー

2023-04-18 06:43 UTC, dino3616 approved these changes

2023-04-18 06:43 UTC, merged